[package]
authors = ["Tom Houlé <tom@tomhoule.com>"]
categories = ["network-programming", "web-programming", "wasm"]
description = "Typed GraphQL requests and responses"
edition = "2018"
keywords = ["graphql", "api", "web", "webassembly", "wasm"]
license = "Apache-2.0 OR MIT"
name = "graphql_client"
repository = "https://github.com/graphql-rust/graphql-client"
version = "0.9.0"

[dependencies]
anyhow = {version = "1.0", optional = true}
doc-comment = "^0.3"
graphql_query_derive = {path = "../graphql_query_derive", version = "0.9.0"}
reqwest = {version = "0.10.7", optional = true, features = ["json"]}
serde = {version = "^1.0.78", features = ["derive"]}
serde_json = "1.0"
thiserror = {version = "1.0", optional = true}

# [target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# reqwest = "0.10.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "^0.2"
wasm-bindgen-futures = "^0.4"
wasm-bindgen-test = "0.3.17"

[dev-dependencies]
reqwest = {features = ["json", "blocking"]}

[features]
web = ["reqwest"]
